/// Flutter icons Wind
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Wind
///      fonts:
///       - asset: fonts/Wind.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class WindIcon {
  WindIcon._();

  static const _kFontFam = 'Wind';
  static const String _kFontPkg = null;

  static const IconData wind = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
